spring:
  profiles.active: local
server:
  port: 9000
security:
  basic:
    enabled: false

management:
  context-path: /manage
  security:
    enabled: false

endpoints:
  env:
    keys-to-sanitize: pwd,uid,password,secret,key,client_id,client_key # suffix or regex

logging:
  level:
    com.netflix: INFO
    org.springframework.cloud: INFO
    io.pivotal.sfdc: DEBUG

info:
  component: Auth Service
  build:
    name: ${project.name:authService}
    description: ${project.description}
    version: ${project.version}
    group: ${project.groupId}
    artifact: ${project.artifactId}

eureka:
  instance:
    #preferIpAddress: false
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
    registryFetchIntervalSeconds: 5
    leaseRenewalIntervalInSeconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true

sfdc:
  client_id: '3MVG9Km_cBLhsuPzBcggzzQasxKNR7xqQaYFvWXTcSdtcdo9TKHY7bsxPrugOgHY9hqLEbYrs7BSneGiiwCDt'
  client_key: '4362547085240312103'
  uid: 's1pdemolounge@gmail.com'
  pwd: 'paasw0rd!RQPePpVLuSDPLosZWGaA40jx'

---
spring:
  profiles: local
  instance:
    nonSecurePort: ${server.port}
  redis:
    host: redis
    port: 6379
eureka:
  instance:
    preferIpAddress: true
    hostname: authservice
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

---
spring:
  profiles: cloud # For deployment in Cloud Foundry
  cloud:
    services:
      registrationMethod: route
eureka:
  instance:
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: ${spring.application.name}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.p-service-registry.credentials.uri}/eureka/
sfdc:
  client_id: 3MVG9A2kN3Bn17hv8siDyJtftcr88aXG3TpBJIqO8QZac_dpXPEoQy08vgi651aB8y6QdfgCkW0HsDIyQeH1V
  client_key: 4631320832041516337
  uid: jigsheth@sfdc.com
  pwd: Pivotal1234mpY9LIqi4zImvqRZI8zYP2p3
